---
title: Bricolage
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: branded
  values:
    image: 
    client: 
    logo: 
    episodes: 
    run-time: 
    listen: 
    link: 
    is-highlight: false
url: https://www.bricolagebakery.co.uk
description: The Bricolage Bakery is a Nottingham artisan bakery. We are passionate
  about sourdough and the lost traditions of our baking ancestors.
permalink: pretty
exclude:
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
company: Bricolage Bakery Ltd
email: info@bricolagebakery.com
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %Y"
future: true
social:
  instagram: https://www.instagram.com/bricolagebakery/
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 12
  limit: 0
  permalink: "/page/:num/"
  title: ":title"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
imgix:
  source: bricolagebakery.imgix.net
